version: "3.9"

services:
  rag-chatbot:
    build: .
    container_name: rag-chatbot
    ports:
      - "8501:8501"           # Streamlit port
    env_file:
      - .env                  # APP_USER and APP_PASS defined here
    volumes:
      - ./data:/app/data      # PDF/DOCX files and FAISS index are persisted
    restart: unless-stopped
  app:
    build: .
    image: gusluer/rag-chatbot:v1
